export enum TableName {
  USERS = "users",
  GAMES = "games",
  PUBLISHERS = "publishers",
  PLATFORMS = "platforms",
  GENRES = "genres",
  PUBLISHER_GAMES = "publisher_games",
  GENRE_GAMES = "genre_games",
  PLATFORM_GAMES = "platform_games",
}

export enum Repositories {
  USERS = "USERS_REPOSITORY",
  GAMES = "GAMES_REPOSITORY",
  PUBLISHERS = "PUBLISHERS_REPOSITORY",
  PLATFORMS = "PLATFORMS_REPOSITORY",
  GENRES = "GENRES_REPOSITORY",
  PUBLISHER_GAMES = "PUBLISHER_GAMES_REPOSITORY",
  GENRE_GAMES = "GENRE_GAMES_REPOSITORY",
  PLATFORM_GAMES = "PLATFORM_GAMES_REPOSITORY",
}
